# Generated by Django 5.1.1 on 2024-10-09 08:00

from django.db import migrations


def create_locations(apps, schema_editor):
    Location = apps.get_model("geo", "Location")
    create = Location.objects.create

    create(name="France/Paris", latitude="48.85341", longitude="2.3488")
    create(name="Germany/Berlin", latitude="52.52437", longitude="13.41053")
    create(name="Ukraine/Kyiv", latitude="50.45466", longitude="30.5238")
    create(name="Ukraine/Lviv", latitude="49.83826", longitude="24.02324")
    create(name="Ukraine/Odessa", latitude="46.48572", longitude="30.74383")
    create(name="United Kingdom/London", latitude="51.50853", longitude="-0.12574")
    create(name="United States/Los Angeles", latitude="34.05223", longitude="-118.24368")
    create(name="United States/New York", latitude="40.71427", longitude="-74.00597")


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_locations),
    ]
