# Generated by Django 5.1.2 on 2024-10-20 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_alter_location_latitude_alter_location_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_user_is_default',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_default',
        ),
        migrations.AddField(
            model_name='defaultlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_for', to='geo.location'),
        ),
        migrations.AddField(
            model_name='defaultlocation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='default_location', to=settings.AUTH_USER_MODEL),
        ),
    ]
